# Generated by Django 5.1.2 on 2024-11-06 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0009_remove_post_likes_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='followers',
        ),
    ]
