# Generated by Django 5.1.2 on 2024-11-08 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0011_profile_bio_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='followers_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
